<?xml version="1.0" encoding="utf-8"?><Database Name="asp" Class="AspTestDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-VAMEF2P\SQLEXPRESS;Initial Catalog=asp;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="aspConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Asptest" Member="Asptest">
    <Type Name="Asptest">
      <Column Name="name" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="id" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="born" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="tel" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="major" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="jianjie" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>