<?xml version="1.0" encoding="utf-8"?><Database Name="asp" Class="OrderDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-VAMEF2P\SQLEXPRESS;Initial Catalog=asp;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="aspConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[Order]" Member="Order">
    <Type Name="Order">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userId" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="commodityId" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="location" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="date" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>